package utilityFiles;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;

public class PayLoad {
	
	
	public static String postPayload()
	{
		return "{\"template\":\"banner-slash.json\",\"country\":\"general\",\"media\":\"mobile\",\"locale\":\"en_us\"}";
	}
	
//Post call Payload	
	public static String fareDetails()
	
	{
	
       
        return "{\"leg\":[{\"originId\":\"MCT\",\"destinationId\":\"DXB\",\"departureFrom\":\"2023-05-14\","
        		+ "\"departureTo\":\"2023-05-19\"},{\"originId\":\"DXB\",\"destinationId\":\"MCT\","
        		+ "\"departureFrom\":\"2023-05-14\",\"departureTo\":\"2023-05-19\"}],\"cabin\":\"Economy\","
        		+ "\"pax\":{\"adult\":1,\"child\":0,\"infant\":0},\"stops\":[],\"airline\":[],"
        		+ "\"timeSlots\":{},\"airports\":{}}";
	}

 public static String getResp()
 {
	 return "{\r\n"
	 		+ "    \"airline\": [\r\n"
	 		+ "        {\r\n"
	 		+ "            \"code\": \"G9\",\r\n"
	 		+ "            \"label\": {\r\n"
	 		+ "                \"en\": \"Air Arabia\",\r\n"
	 		+ "                \"ar\": \"العربية للطيران\"\r\n"
	 		+ "            }\r\n"
	 		+ "        },\r\n"
	 		+ "        {\r\n"
	 		+ "            \"code\": \"QR\",\r\n"
	 		+ "            \"label\": {\r\n"
	 		+ "                \"en\": \"Qatar Airways\",\r\n"
	 		+ "                \"ar\": \"الخطوط الجوية القطرية\"\r\n"
	 		+ "            }\r\n"
	 		+ "        },\r\n"
	 		+ "        {\r\n"
	 		+ "            \"code\": \"3L\",\r\n"
	 		+ "            \"label\": {\r\n"
	 		+ "                \"en\": \"AirArabia Abu Dhabi\",\r\n"
	 		+ "                \"ar\": \"الخطوط العربية أبو ظبي\"\r\n"
	 		+ "            }\r\n"
	 		+ "        },\r\n"
	 		+ "        {\r\n"
	 		+ "            \"code\": \"EY\",\r\n"
	 		+ "            \"label\": {\r\n"
	 		+ "                \"en\": \"Etihad Airways\",\r\n"
	 		+ "                \"ar\": \"طيران الاتحاد\"\r\n"
	 		+ "            }\r\n"
	 		+ "        },\r\n"
	 		+ "        {\r\n"
	 		+ "            \"code\": \"WY\",\r\n"
	 		+ "            \"label\": {\r\n"
	 		+ "                \"en\": \"Oman Air\",\r\n"
	 		+ "                \"ar\": \"الطيران العماني\"\r\n"
	 		+ "            }\r\n"
	 		+ "        },\r\n"
	 		+ "        {\r\n"
	 		+ "            \"code\": \"FZ\",\r\n"
	 		+ "            \"label\": {\r\n"
	 		+ "                \"en\": \"Flydubai\",\r\n"
	 		+ "                \"ar\": \"فلاي دبي\"\r\n"
	 		+ "            }\r\n"
	 		+ "        },\r\n"
	 		+ "        {\r\n"
	 		+ "            \"code\": \"EK\",\r\n"
	 		+ "            \"label\": {\r\n"
	 		+ "                \"en\": \"Emirates\",\r\n"
	 		+ "                \"ar\": \"طيران الإمارات\"\r\n"
	 		+ "            }\r\n"
	 		+ "        },\r\n"
	 		+ "        {\r\n"
	 		+ "            \"code\": \"GF\",\r\n"
	 		+ "            \"label\": {\r\n"
	 		+ "                \"en\": \"Gulf Air\",\r\n"
	 		+ "                \"ar\": \"طيران الخليج\"\r\n"
	 		+ "            }\r\n"
	 		+ "        },\r\n"
	 		+ "        {\r\n"
	 		+ "            \"code\": \"ET\",\r\n"
	 		+ "            \"label\": {\r\n"
	 		+ "                \"en\": \"Ethiopian Airlines\",\r\n"
	 		+ "                \"ar\": \"الخطوط الجوية الأثيوبية\"\r\n"
	 		+ "            }\r\n"
	 		+ "        }\r\n"
	 		+ "    ],\r\n"
	 		+ "    \"airport\": [\r\n"
	 		+ "        {\r\n"
	 		+ "            \"code\": \"MCT\",\r\n"
	 		+ "            \"tz\": \"Asia/Muscat\",\r\n"
	 		+ "            \"timeZone\": \"4.00\",\r\n"
	 		+ "            \"type\": \"2\",\r\n"
	 		+ "            \"label\": {\r\n"
	 		+ "                \"en\": \"Seeb International Airport\",\r\n"
	 		+ "                \"ar\": \"مطار سيب الدولي\"\r\n"
	 		+ "            },\r\n"
	 		+ "            \"country\": {\r\n"
	 		+ "                \"label\": {\r\n"
	 		+ "                    \"en\": \"Oman\",\r\n"
	 		+ "                    \"ar\": \"عُمان\"\r\n"
	 		+ "                },\r\n"
	 		+ "                \"code\": \"OM\"\r\n"
	 		+ "            },\r\n"
	 		+ "            \"city\": {\r\n"
	 		+ "                \"en\": \"Muscat\",\r\n"
	 		+ "                \"ar\": \"مسقط\"\r\n"
	 		+ "            }\r\n"
	 		+ "        },\r\n"
	 		+ "        {\r\n"
	 		+ "            \"code\": \"DXB\",\r\n"
	 		+ "            \"tz\": \"Asia/Dubai\",\r\n"
	 		+ "            \"timeZone\": \"4.00\",\r\n"
	 		+ "            \"type\": \"1\",\r\n"
	 		+ "            \"label\": {\r\n"
	 		+ "                \"en\": \"Dubai International Airport\",\r\n"
	 		+ "                \"ar\": \"مطار دبي الدولي\"\r\n"
	 		+ "            },\r\n"
	 		+ "            \"country\": {\r\n"
	 		+ "                \"label\": {\r\n"
	 		+ "                    \"en\": \"United Arab Emirates\",\r\n"
	 		+ "                    \"ar\": \"الإمارات العربية المتحدة\"\r\n"
	 		+ "                },\r\n"
	 		+ "                \"code\": \"AE\"\r\n"
	 		+ "            },\r\n"
	 		+ "            \"city\": {\r\n"
	 		+ "                \"en\": \"Dubai\",\r\n"
	 		+ "                \"ar\": \"دبى\"\r\n"
	 		+ "            }\r\n"
	 		+ "        },\r\n"
	 		+ "        {\r\n"
	 		+ "            \"code\": \"SHJ\",\r\n"
	 		+ "            \"tz\": \"Asia/Dubai\",\r\n"
	 		+ "            \"timeZone\": \"4.00\",\r\n"
	 		+ "            \"type\": \"2\",\r\n"
	 		+ "            \"label\": {\r\n"
	 		+ "                \"en\": \"Sharjah International Airport\",\r\n"
	 		+ "                \"ar\": \"مطار الشارقة\"\r\n"
	 		+ "            },\r\n"
	 		+ "            \"country\": {\r\n"
	 		+ "                \"label\": {\r\n"
	 		+ "                    \"en\": \"United Arab Emirates\",\r\n"
	 		+ "                    \"ar\": \"الإمارات العربية المتحدة\"\r\n"
	 		+ "                },\r\n"
	 		+ "                \"code\": \"AE\"\r\n"
	 		+ "            },\r\n"
	 		+ "            \"city\": {\r\n"
	 		+ "                \"en\": \"Sharjah\",\r\n"
	 		+ "                \"ar\": \"الشارقة\"\r\n"
	 		+ "            }\r\n"
	 		+ "        },\r\n"
	 		+ "        {\r\n"
	 		+ "            \"code\": \"DOH\",\r\n"
	 		+ "            \"tz\": \"Asia/Qatar\",\r\n"
	 		+ "            \"timeZone\": \"3.00\",\r\n"
	 		+ "            \"type\": \"1\",\r\n"
	 		+ "            \"label\": {\r\n"
	 		+ "                \"en\": \"Hamad International Airport\",\r\n"
	 		+ "                \"ar\": \"مطار حمد الدولي\"\r\n"
	 		+ "            },\r\n"
	 		+ "            \"country\": {\r\n"
	 		+ "                \"label\": {\r\n"
	 		+ "                    \"en\": \"Qatar\",\r\n"
	 		+ "                    \"ar\": \"قطر\"\r\n"
	 		+ "                },\r\n"
	 		+ "                \"code\": \"QA\"\r\n"
	 		+ "            },\r\n"
	 		+ "            \"city\": {\r\n"
	 		+ "                \"en\": \"Doha\",\r\n"
	 		+ "                \"ar\": \"الدوحة\"\r\n"
	 		+ "            }\r\n"
	 		+ "        },\r\n"
	 		+ "        {\r\n"
	 		+ "            \"code\": \"AUH\",\r\n"
	 		+ "            \"tz\": \"Asia/Dubai\",\r\n"
	 		+ "            \"timeZone\": \"4.00\",\r\n"
	 		+ "            \"type\": \"2\",\r\n"
	 		+ "            \"label\": {\r\n"
	 		+ "                \"en\": \"Abu Dhabi International Airport\",\r\n"
	 		+ "                \"ar\": \"مطار أبو ظبي الدولي\"\r\n"
	 		+ "            },\r\n"
	 		+ "            \"country\": {\r\n"
	 		+ "                \"label\": {\r\n"
	 		+ "                    \"en\": \"United Arab Emirates\",\r\n"
	 		+ "                    \"ar\": \"الإمارات العربية المتحدة\"\r\n"
	 		+ "                },\r\n"
	 		+ "                \"code\": \"AE\"\r\n"
	 		+ "            },\r\n"
	 		+ "            \"city\": {\r\n"
	 		+ "                \"en\": \"Abu Dhabi\",\r\n"
	 		+ "                \"ar\": \"ابو ظبي\"\r\n"
	 		+ "            }\r\n"
	 		+ "        },\r\n"
	 		+ "        {\r\n"
	 		+ "            \"code\": \"XNB\",\r\n"
	 		+ "            \"tz\": \"Asia/Dubai\",\r\n"
	 		+ "            \"timeZone\": \"\",\r\n"
	 		+ "            \"type\": \"7\",\r\n"
	 		+ "            \"label\": {\r\n"
	 		+ "                \"en\": \"Dubai, United Arab Emirates (XNB-Dubai Bus Station)\",\r\n"
	 		+ "                \"ar\": \"دبي (XNB - محطة الأتوبيس بدبي)\"\r\n"
	 		+ "            },\r\n"
	 		+ "            \"country\": {\r\n"
	 		+ "                \"label\": {\r\n"
	 		+ "                    \"en\": \"United Arab Emirates\",\r\n"
	 		+ "                    \"ar\": \"الإمارات العربية المتحدة\"\r\n"
	 		+ "                },\r\n"
	 		+ "                \"code\": \"AE\"\r\n"
	 		+ "            },\r\n"
	 		+ "            \"city\": {\r\n"
	 		+ "                \"en\": \"Dubai\",\r\n"
	 		+ "                \"ar\": \"دبي\"\r\n"
	 		+ "            }\r\n"
	 		+ "        },\r\n"
	 		+ "        {\r\n"
	 		+ "            \"code\": \"BAH\",\r\n"
	 		+ "            \"tz\": \"Asia/Bahrain\",\r\n"
	 		+ "            \"timeZone\": \"3.00\",\r\n"
	 		+ "            \"type\": \"2\",\r\n"
	 		+ "            \"label\": {\r\n"
	 		+ "                \"en\": \"Bahrain International Airport\",\r\n"
	 		+ "                \"ar\": \"مطار البحرين الدولي\"\r\n"
	 		+ "            },\r\n"
	 		+ "            \"country\": {\r\n"
	 		+ "                \"label\": {\r\n"
	 		+ "                    \"en\": \"Bahrain\",\r\n"
	 		+ "                    \"ar\": \"البحرين\"\r\n"
	 		+ "                },\r\n"
	 		+ "                \"code\": \"BH\"\r\n"
	 		+ "            },\r\n"
	 		+ "            \"city\": {\r\n"
	 		+ "                \"en\": \"Bahrain\",\r\n"
	 		+ "                \"ar\": \"المنامة\"\r\n"
	 		+ "            }\r\n"
	 		+ "        },\r\n"
	 		+ "        {\r\n"
	 		+ "            \"code\": \"ADD\",\r\n"
	 		+ "            \"tz\": \"Africa/Addis_Ababa\",\r\n"
	 		+ "            \"timeZone\": \"3.00\",\r\n"
	 		+ "            \"type\": \"3\",\r\n"
	 		+ "            \"label\": {\r\n"
	 		+ "                \"en\": \"Addis Ababa Bole International Airport\",\r\n"
	 		+ "                \"ar\": \"مطار أديس أبابا الدولي\"\r\n"
	 		+ "            },\r\n"
	 		+ "            \"country\": {\r\n"
	 		+ "                \"label\": {\r\n"
	 		+ "                    \"en\": \"Ethiopia\",\r\n"
	 		+ "                    \"ar\": \"أثيوبيا\"\r\n"
	 		+ "                },\r\n"
	 		+ "                \"code\": \"ET\"\r\n"
	 		+ "            },\r\n"
	 		+ "            \"city\": {\r\n"
	 		+ "                \"en\": \"Addis Ababa\",\r\n"
	 		+ "                \"ar\": \"اديس ابابا\"\r\n"
	 		+ "            }\r\n"
	 		+ "        }\r\n"
	 		+ "    ]\r\n"
	 		+ "}";
 }
}
